version: '3'

services:
  web:
    build:
      context: ./backend
    env_file:
      - .env
    environment:
      - CONN_STR=mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@cakeshop.9kc7omy.mongodb.net/?retryWrites=true&w=majority  
    ports:
      - 8000:8000
    volumes:
      - ./backend/app:/backend/app
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    restart: always
    env_file:
      - .env
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGODB_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db